name: GenerateSlides

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: 
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: build slides
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"

      - name: install markdown slides
        run: python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git

      - name: generate markdown slides
        run: mdslides ./slides.md --output_dir slides

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./slides

  deploy:
    environment:
      name: github-pages
      url: $ {{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v4